USE todolist;

INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task a', '2018-04-28', FALSE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task b', '2018-04-29', FALSE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task c', '2018-04-30', FALSE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task d', '2018-05-01', FALSE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task e', '2018-05-02', FALSE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task f', '2018-05-03', FALSE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task g', '2018-05-04', FALSE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task h', '2018-05-05', FALSE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task i', '2018-05-06', FALSE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task j', '2018-05-07', FALSE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task k', '2018-05-08', FALSE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task l', '2018-05-09', FALSE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task m', '2018-05-10', FALSE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task n', '2018-05-11', FALSE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task o', '2018-05-12', FALSE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task p', '2018-05-28', FALSE, TRUE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task q', '2018-05-28', FALSE, TRUE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task r', '2018-05-28', FALSE, TRUE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task s', '2018-05-28', FALSE, TRUE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task t', '2018-05-28', FALSE, TRUE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task u', '2018-05-28', TRUE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task v', '2018-05-28', TRUE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task w', '2018-05-28', TRUE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task x', '2018-05-28', TRUE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task y', '2018-05-28', TRUE, FALSE);
INSERT INTO task (task_label, task_duedate, task_isCompleted, task_isCancelled) VALUES ('task z', '2018-05-28', FALSE, FALSE);
INSERT INTO tag (task_id, tag_name) VALUES (1, 'school');
INSERT INTO tag (task_id, tag_name) VALUES (2, 'school');
INSERT INTO tag (task_id, tag_name) VALUES (3, 'school');
INSERT INTO tag (task_id, tag_name) VALUES (4, 'school');
INSERT INTO tag (task_id, tag_name) VALUES (5, 'school');
INSERT INTO tag (task_id, tag_name) VALUES (6, 'school');
INSERT INTO tag (task_id, tag_name) VALUES (7, 'school');
INSERT INTO tag (task_id, tag_name) VALUES (8, 'school');
INSERT INTO tag (task_id, tag_name) VALUES (9, 'school');
INSERT INTO tag (task_id, tag_name) VALUES (10, 'school');
INSERT INTO tag (task_id, tag_name) VALUES (6, 'work');
INSERT INTO tag (task_id, tag_name) VALUES (7, 'work');
INSERT INTO tag (task_id, tag_name) VALUES (8, 'work');
INSERT INTO tag (task_id, tag_name) VALUES (9, 'work');
INSERT INTO tag (task_id, tag_name) VALUES (10, 'work');
INSERT INTO tag (task_id, tag_name) VALUES (21, 'school');
INSERT INTO tag (task_id, tag_name) VALUES (22, 'school');
INSERT INTO tag (task_id, tag_name) VALUES (23, 'school');
INSERT INTO tag (task_id, tag_name) VALUES (24, 'school');
INSERT INTO tag (task_id, tag_name) VALUES (25, 'school');